name: dart_queue
description: A simple implementation of a task processing queue in Dart.
version: 0.0.1+1
repository: https://github.com/iamngoni/dart_queue
homepage: https://github.com/iamngoni/dart_queue

environment:
  sdk: '>=3.5.0-160.0.dev <4.0.0'

dev_dependencies:
  test: 1.25.7
  very_good_analysis: ^5.0.1